# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0e5f7e4617640de71ead778036f3d8430f2024238fbbe87f6b87d15bb31ebe1a8f6882b826097facdc74496e20d698332d0ce3641c336b91d4e9a0f29279ab1

test:
  secret_key_base: 7514894ae4455013cb8730ac03ee1fc98045db102d81ac2fa81cf8c4047165ff7e4ad607bd2ea289ad80ce32b46337e2c76ed22a1720e575a9f2889189c0f35d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
